Add LeetCode-1 (different approach) and LeetCode-167 in C++
Tahanima/leetcode-solution-curation pull request #46
Opened 2021-08-06 12:20 UTC by r8025n

resolves #42

2021-08-11 13:25 UTC, Tahanima requested changes
Hi @r8025n 
Please resolve all the requested changes. Also, change the folder name from `167_TwoSum II` to `167_TwoSumII`

2021-08-11 13:25 UTC, Tahanima commented on Algorithms/Easy/1_TwoSum/SolutionOne.cpp
> +        vector<pair<int,int>> valueIndexPair;
Change this code to 
```cpp
vector<pair<int, int>> valueIndexPair;
```

2021-08-11 13:25 UTC, Tahanima commented on Algorithms/Easy/1_TwoSum/SolutionOne.cpp
> +	    int index1, index2, sum;
Fix the indentation.

2021-08-11 13:25 UTC, Tahanima commented on Algorithms/Easy/1_TwoSum/SolutionOne.cpp
> +            valueIndexPair.push_back(pair<int,int>(nums[k], k));
Change this code to
```cpp
valueIndexPair.push_back(pair<int, int>(nums[k], k));
```

2021-08-11 13:25 UTC, Tahanima commented on Algorithms/Easy/1_TwoSum/SolutionOne.cpp
> +	    index1 = 0;
Fix indentation

2021-08-11 13:25 UTC, Tahanima commented on Algorithms/Easy/1_TwoSum/SolutionOne.cpp
> +	    index2 = valueIndexPair.size() - 1;
Fix indentation

2021-08-11 13:25 UTC, Tahanima commented on Algorithms/Easy/1_TwoSum/SolutionOne.cpp
> +	        if(sum == target)
Fix indentation

2021-08-13 07:35 UTC, r8025n commented
HI,
Thank you for your feedback. I have addressed the requested changes, please review.

2021-08-14 18:51 UTC, Tahanima requested changes
Hi @r8025n 
Please fix all the indentation issues.

2021-08-14 18:51 UTC, Tahanima commented on Algorithms/Easy/1_TwoSum/SolutionOne.cpp
> +	vector<int> answer;
Need to fix the indentation.

2021-08-14 18:51 UTC, Tahanima commented on Algorithms/Easy/1_TwoSum/SolutionOne.cpp
> +	int index1, index2, sum;
Need to fix the indentation.

2021-08-14 18:51 UTC, Tahanima commented on Algorithms/Easy/1_TwoSum/SolutionOne.cpp
> +	index1 = 0;
Need to fix the indentation.

2021-08-14 18:51 UTC, Tahanima commented on Algorithms/Easy/1_TwoSum/SolutionOne.cpp
> +	index2 = valueIndexPair.size() - 1;
Need to fix the indentation.

2021-08-14 18:51 UTC, Tahanima commented on Algorithms/Easy/1_TwoSum/SolutionOne.cpp
> +
Need to fix the indentation of the if-else block.

2021-08-15 20:28 UTC, r8025n commented
Hi @Tahanima 
I am kind of lost now, could you please help me out  and point me to the right direction? As your recent requested changes are suggesting there are indentation issues in my code but in my forked repo the code looks okay. What am I missing here?

What I did so far:
1. Opened a pull request. 
2. Some changes were requested by you.
3. Addressed the requested changes in my local git repo, updated my repo with the original upstream repo by fetching and merging, then pushed them to my forked repo.
4. And now as you addressed some indentation issues, as I visited my fork repo they seems fine there!!

So did I miss any steps after pushing the first requested changes to my forked repo?

2021-08-17 09:48 UTC, Tahanima approved these changes
@r8025n I get your point. No worries. I'll fix the indentation after merging. Keep up the good work! 😃

2021-08-17 09:48 UTC, merged

2021-08-18 06:13 UTC, r8025n commented
Thank You :)